"""
Player Performance Analysis using xP and POE metrics.

This script analyzes player-level performance by aggregating Expected Points (xP)
and Points Over Expected (POE) from the enriched shot dataset.

Usage:
    python player_performance_analysis.py

Requires:
    - shots_with_xp_*.parquet generated by expected_points_analysis.py
"""

import sys
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt

# Add analysis directory to path to allow imports if run from root
ANALYSIS_DIR = Path(__file__).parent
sys.path.append(str(ANALYSIS_DIR))

# Import from utils
from utils.court_utils import draw_half_court, setup_shot_chart_axes


# Configuration
DATA_DIR = ANALYSIS_DIR / "data"
FIGURES_DIR = ANALYSIS_DIR / "figures"
DEFAULT_SEASON = '2025-26'


def load_enriched_shots(season=DEFAULT_SEASON):
    """
    Load the enriched shot dataset with xP and POE values.
    
    Args:
        season: Season identifier
        
    Returns:
        DataFrame with shot data including xP and POE
    """
    data_path = DATA_DIR / f'shots_with_xp_{season}.parquet'
    
    if not data_path.exists():
        raise FileNotFoundError(
            f"Enriched data not found at {data_path}. "
            f"Run expected_points_analysis.py first."
        )
    
    return pd.read_parquet(data_path)


def compute_player_summary(shots_df, min_attempts=250):
    """
    Aggregate performance metrics by player.
    
    Args:
        shots_df: Shot DataFrame with xP and POE
        min_attempts: Minimum shot attempts to include player
        
    Returns:
        DataFrame with player-level aggregations
    """
    summary = shots_df.groupby('PLAYER_NAME').agg(
        total_attempts=('SHOT_MADE_FLAG', 'count'),
        total_makes=('SHOT_MADE_FLAG', 'sum'),
        total_poe=('POE', 'sum'),
        total_xp=('xP_value', 'sum'),
        total_actual_points=('actual_points', 'sum'),
        avg_xp_prob=('xP_prob', 'mean')
    ).reset_index()
    
    # Filter by minimum attempts
    summary = summary[summary['total_attempts'] >= min_attempts].copy()
    
    # Derived metrics
    summary['fg_pct'] = summary['total_makes'] / summary['total_attempts']
    summary['poe_per_100'] = (summary['total_poe'] / summary['total_attempts']) * 100
    summary['shooting_skill'] = summary['fg_pct'] - summary['avg_xp_prob']
    summary['expected_fg_pct'] = summary['avg_xp_prob']
    summary['fg_residual'] = summary['shooting_skill']
    summary['fg_residual_pct'] = summary['fg_residual'] * 100
    
    return summary


def print_leaderboards(summary, n=15):
    """
    Print top and bottom performers by POE.
    
    Args:
        summary: Player summary DataFrame
        n: Number of players to show
    """
    display_cols = ['PLAYER_NAME', 'total_attempts', 'fg_pct', 'total_poe', 'poe_per_100']
    formatters = {
        'fg_pct': '{:.1%}'.format,
        'total_poe': '{:.1f}'.format,
        'poe_per_100': '{:.2f}'.format
    }
    
    print(f"\n{'='*60}")
    print(f"TOP {n} PLAYERS BY TOTAL POINTS OVER EXPECTED")
    print(f"{'='*60}")
    top = summary.nlargest(n, 'total_poe')[display_cols]
    print(top.to_string(index=False, formatters=formatters))
    
    print(f"\n{'='*60}")
    print(f"BOTTOM {n} PLAYERS BY TOTAL POINTS OVER EXPECTED")
    print(f"{'='*60}")
    bottom = summary.nsmallest(n, 'total_poe')[display_cols]
    print(bottom.to_string(index=False, formatters=formatters))


def generate_player_shot_chart(shots_df, player_name, season, output_dir=None):
    """
    Generate POE-colored shot chart for a specific player.
    
    Args:
        shots_df: Shot DataFrame with POE
        player_name: Player to visualize
        season: Season identifier
    output_dir: Output directory (defaults to figures/)
    """
    if output_dir is None:
        output_dir = FIGURES_DIR
    
    player_shots = shots_df[shots_df['PLAYER_NAME'] == player_name]
    
    if player_shots.empty:
        print(f"No shots found for {player_name}")
        return
    
    plt.style.use('fivethirtyeight')
    fig, ax = plt.subplots(figsize=(12, 11))
    
    draw_half_court(ax, outer_lines=True)
    
    made = player_shots[player_shots['SHOT_MADE_FLAG'] == 1]
    missed = player_shots[player_shots['SHOT_MADE_FLAG'] == 0]
    
    # Plot with POE coloring
    scatter_made = ax.scatter(
        made['LOC_X'], made['LOC_Y'],
        c=made['POE'], cmap='coolwarm',
        marker='*', s=100, alpha=0.8,
        label='Made Shot',
        vmin=-2, vmax=2
    )
    
    ax.scatter(
        missed['LOC_X'], missed['LOC_Y'],
        c=missed['POE'], cmap='coolwarm',
        marker='o', s=50, alpha=0.6,
        label='Missed Shot',
        vmin=-2, vmax=2
    )
    
    cbar = fig.colorbar(scatter_made, ax=ax, shrink=0.6)
    cbar.set_label('Points Over Expected (POE)', fontsize=12)
    
    ax.legend(loc='upper left', fontsize=10)
    setup_shot_chart_axes(ax)
    ax.set_title(f'{player_name} Shot Value Chart ({season})', fontsize=18)
    
    safe_name = player_name.replace(' ', '_').replace('.', '')
    output_path = Path(output_dir) / f'{safe_name}_poe_shotchart.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"Saved: {output_path}")
    plt.close()


if __name__ == "__main__":
    DATA_DIR.mkdir(exist_ok=True)
    FIGURES_DIR.mkdir(exist_ok=True)
    
    print("Loading enriched shot data...")
    shots_df = load_enriched_shots()
    print(f"Loaded {len(shots_df):,} shots")
    
    # Compute player summaries
    print("\nComputing player metrics...")
    min_shots = 250
    player_summary = compute_player_summary(shots_df, min_attempts=min_shots)
    print(f"Found {len(player_summary)} players with {min_shots}+ attempts")
    
    # Print leaderboards
    print_leaderboards(player_summary)
    
    # Generate shot chart for top performer
    if not player_summary.empty:
        top_player = player_summary.nlargest(1, 'total_poe')['PLAYER_NAME'].iloc[0]
        print(f"\nGenerating shot chart for top performer: {top_player}")
        generate_player_shot_chart(shots_df, top_player, DEFAULT_SEASON, FIGURES_DIR)
    
    # Save summary to CSV
    output_path = DATA_DIR / 'player_summary.csv'
    player_summary.to_csv(output_path, index=False)
    print(f"\nPlayer summary saved to: {output_path}")
